CREATE DATABASE face_app;
USE face_app;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(50) UNIQUE NOT NULL,
    entries INT DEFAULT 0,
    signup_date TIMESTAMP NOT NULL
);

CREATE TABLE signin (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hash_pwd VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL
);